export default {
    red: '#880000',
    transparentRed: 'rgba(200, 0, 0, 0.5)',
    errorBackground: 'transparent',
    darkGrey: '#888888',
    lightGrey: '#CCCCCC',
    lighterGrey: '#DDDDDD',
    white: '#FFFFFF',
    previewOverlay: 'rgba(0, 0, 0, 0.5)',
    inactiveTouchableUnderlayColor: 'rgba(0, 0, 0, 0.4)',
    separator: 'rgba(0, 0, 0, 0.3)',
    touchableUnderlayColor: 'rgba(0, 0, 0, 0.2)',
    reallyLightTransparentGrey: 'rgba(0, 0, 0, 0.1)',
    transparent: 'transparent',
    black: '#000000',
};
